//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Template_Design
    {
        public int Form_Field_ID { get; set; }
        public Nullable<int> Form_Template_ID { get; set; }
        public string Form_Field_Name { get; set; }
        public string Form_Field_Type { get; set; }
        public string Data_Field_Name { get; set; }
        public string Data_Field_Type { get; set; }
        public Nullable<bool> Field_Mandatory { get; set; }
        public Nullable<bool> Field_HistoryIdentifier { get; set; }
        public string Content { get; set; }
        public Nullable<short> Width { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Left { get; set; }
        public Nullable<short> Top { get; set; }
        public string Font { get; set; }
        public string Font_Color { get; set; }
        public Nullable<int> Font_Size { get; set; }
        public string Font_Bold { get; set; }
        public string Background_Color { get; set; }
        public string Text_Placeholder { get; set; }
        public Nullable<short> rows { get; set; }
        public string Enumerations { get; set; }
        public string Select_Items { get; set; }
        public string Complex_Type_Name { get; set; }
        public string Display_Name { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
