//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Template_Master
    {
        public int Form_Template_ID { get; set; }
        public string Form_Template_Name { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Department_ID { get; set; }
        public Nullable<int> Survey_Type_ID { get; set; }
        public string Form_Entity { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
