//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey_Item_Master
    {
        public string Reference_Number { get; set; }
        public Nullable<long> Surveyor_User_ID { get; set; }
        public Nullable<System.DateTime> Inspection_date { get; set; }
        public Nullable<int> Survey_Rating { get; set; }
        public Nullable<bool> Commission { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
