//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncData
    {
        public int Sync_ID { get; set; }
        public string Device_Code { get; set; }
        public string Sync_Entity { get; set; }
        public Nullable<long> Record_ID { get; set; }
        public bool NeedSync { get; set; }
    }
}
