//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTicket
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> SurveyTypeId { get; set; }
        public Nullable<long> StatusReasonId { get; set; }
        public Nullable<long> PriorityId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> TicketCreatedDate { get; set; }
        public Nullable<System.DateTime> TicketSubmissionDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> CustomerAvailableFrom { get; set; }
        public Nullable<System.DateTime> CustomerAvailableTo { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Department Department { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual StatusReason StatusReason { get; set; }
        public virtual SurveyType SurveyType { get; set; }
        public virtual User User { get; set; }
    }
}
