//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace valuware.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class formDesignEntities : DbContext
    {
        public formDesignEntities()
            : base("name=formDesignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Master> Client_Master { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Form_Template_Design> Form_Template_Design { get; set; }
        public virtual DbSet<Form_Template_Master> Form_Template_Master { get; set; }
        public virtual DbSet<Survey_Types> Survey_Types { get; set; }
    }
}
