//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace valuware.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QualityEntities : DbContext
    {
        public QualityEntities()
            : base("name=QualityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Service_Tickets> Service_Tickets { get; set; }
        public virtual DbSet<Survey_Item_Master> Survey_Item_Master { get; set; }
    
        public virtual int getFormDesignData(string referenceNumber)
        {
            var referenceNumberParameter = referenceNumber != null ?
                new ObjectParameter("ReferenceNumber", referenceNumber) :
                new ObjectParameter("ReferenceNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getFormDesignData", referenceNumberParameter);
        }
    
        public virtual ObjectResult<getSurveyItemMasterInfo_Result> getSurveyItemMasterInfo(string referenceNumber)
        {
            var referenceNumberParameter = referenceNumber != null ?
                new ObjectParameter("ReferenceNumber", referenceNumber) :
                new ObjectParameter("ReferenceNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSurveyItemMasterInfo_Result>("getSurveyItemMasterInfo", referenceNumberParameter);
        }
    
        public virtual ObjectResult<getQualityListing_Result> getQualityListing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getQualityListing_Result>("getQualityListing");
        }
    }
}
