//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace valuware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Tickets
    {
        public int Service_Ticket_ID { get; set; }
        public int Client_ID { get; set; }
        public int Department_ID { get; set; }
        public int Status { get; set; }
        public int Survey_Type_ID { get; set; }
        public string Valuation_Item { get; set; }
        public Nullable<int> Status_Reason { get; set; }
        public string Reference_Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public int Surveyor_ID { get; set; }
        public Nullable<System.DateTime> Cust_Available_From { get; set; }
        public Nullable<System.DateTime> Cust_Available_To { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Address { get; set; }
        public string Cust_Location { get; set; }
        public string Cust_Landline { get; set; }
        public string Cust_Mobile { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
