//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace valuware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey_Types
    {
        public int Survey_Type_ID { get; set; }
        public string Survey_Type_Name { get; set; }
        public string Survey_Type_Code { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
    }
}
